### ISSUE TITLE
Write documents 

### ISSUE THREAD

**Issue by Elsavid** [meyruiz/MACS-Soen6011summer2023#24]
Document(s) with 
1. 4 user stories backlog for Sprint1 
2. Task Breakdown (details of the stories with team 
members responsibility, if known, for the current 
sprint). 
3. Open issues or plan for next Sprint

**Comment by Elsavid** [comment]
Meetings Minutes file (minutes files should be named 
<teamName_Sprint#_meetingnumber_meetingd ate>

**Comment by Alor-e** [comment]
Please does the Task Breakdown document refer to the one I put on wiki too.

**Comment by Elsavid** [comment]
All three tasks are completed. Sprint 1 documentation defined on wiki.
