### ISSUE TITLE
write documents for task Breakdown 

### ISSUE THREAD

**Issue by Elsavid** [meyruiz/MACS-Soen6011summer2023#27]
Requirement: 
Details of the stories with team members responsibility, if known, for the current sprint. 

This issue is related to https://github.com/meyruiz/MACS-Soen6011summer2023/issues/24

**Comment by paullmq8** [comment]
I've completed all the task breakdown for the four main user stories for Sprint 1 #3 #4 #5 #6

**Comment by paullmq8** [comment]
Related task breakdown are done both in the report and in the Issues section of github.
