### ISSUE TITLE
As a user, I can register into the system, so that I can access the career platform to obtain the information that I need.

### ISSUE THREAD

**Issue by paullmq8** [meyruiz/MACS-Soen6011summer2023#3]
**Description**
As a visitor, I can register into the system, so that I can access the career platform to obtain the information that I need.
I need to provide my email and password to register

Story point : 7
Risk : Low
This feature is easy to implement and ensure new accounts are created securely with security measures like hashing the password. This risk can be avoided with encryption.

**Comment by JoumanaDargham** [comment]
this user story is a little vague... What kind of user? what kind of info

**Comment by paullmq8** [comment]
@JoumanaDargham , Hi prof, yes it's indeed vague here to use user here. I've changed it into visitor since they don't have accounts at the moment. Is it ok?

**Comment by JoumanaDargham** [comment]
No problem...
It is only a comment

**Comment by SecretAgentShh** [comment]
Added Story points and risk management

**Comment by Elsavid** [comment]
Completed
