### ISSUE TITLE
Track the work of sprint 1 on wiki 

### ISSUE THREAD

**Issue by Elsavid** [meyruiz/MACS-Soen6011summer2023#32]

**Comment by paullmq8** [comment]
I've finished the task breakdown for the four main user stories.

**Comment by Alor-e** [comment]
I have added the user stories.

**Comment by SecretAgentShh** [comment]
I have updated the readme file with project description

**Comment by Elsavid** [comment]
I have drafted the readme file and organized documentation.

**Comment by AutoSleep** [comment]
The report for the Delivery 1 is done and submitted to the moodle

**Comment by meyruiz** [comment]
I've created the minutes for all our meetings and I've helped creating the user stories definition
