### ISSUE TITLE
As a user, I can login and logout so I can access my account anywhere.

### ISSUE THREAD

**Issue by paullmq8** [meyruiz/MACS-Soen6011summer2023#4]
**Description**
As a user, I can login and logout so I can access my account anywhere.

Related tasks:
#7 
#10 
#11 
#12 
#14 
#15 
Story point: 15
Risk: Low
Ensuring the account details are stored correctly otherwise the user may lose access to the account. This is mitigated by using a database to store and retrieve data efficiently like MongoDB.

**Comment by SecretAgentShh** [comment]
Added story points and risk management

**Comment by Elsavid** [comment]
Login and logout finished
