### ISSUE TITLE
As an employer, I can create/get/edit/delete a job posting so that I can attract qualified candidates and effectively communicate the job details and requirements.

### ISSUE THREAD

**Issue by paullmq8** [meyruiz/MACS-Soen6011summer2023#5]
**Description**
As an employer, I can create a job posting so that I can attract qualified candidates and effectively communicate the job details and requirements along with number of positions open.

Related issues:
#16 #17
Story point: 11
Risk : Medium
It is important to show jobs that have open positions and display job descriptions correctly for candidates to apply. This risk can be avoided by assigning each job an ID to keep track of its details.

**Comment by SecretAgentShh** [comment]
Added Story points and risk management

**Comment by Elsavid** [comment]
Employer should be able to create jobs
