### ISSUE TITLE
As an employer, I want to browse candidates so I can see who has applied with the job description.

### ISSUE THREAD

**Issue by Elsavid** [meyruiz/MACS-Soen6011summer2023#51]
As an employer, I can browse candidiates who have applied fot the jobs and see their profile and resume .
Related tasks:

#53 
#76 
Story point: 9
Risk probability: High
If the tracking is not implemented correctly candidates who match the job requirements may fail to receive an interview offer reducing the effectiveness of the platform. This risk can be mitigated by making sure tracking is done properly.

**Comment by SecretAgentShh** [comment]
Added story points and risk management

**Comment by Elsavid** [comment]
Employer can browse candidates now

**Comment by Elsavid** [comment]
Completed
