### ISSUE TITLE
As a student/candidate, I can see all available job postings and apply to the jobs I’m interested in.

### ISSUE THREAD

**Issue by Elsavid** [meyruiz/MACS-Soen6011summer2023#54]
As a student/candidate, I can browse job postings  that are open and apply for the job with resume. 

Related tasks:
#55 
#56 
#78 
#67 
Story point : 18
Risk: High
A job can be applied to only if it is open so it is important to keep the database updated and display jobs that are open only to avoid inconsistency. This risk has to be avoided by regular tracking of open positions in a job to mark it as open or closed to apply

**Comment by SecretAgentShh** [comment]
Added Story points and risk management

**Comment by Elsavid** [comment]
Finish students browsing jobs and applying for jobs
